import { MigrationInterface, QueryRunner } from "typeorm";

export class Initial1779845425309 implements MigrationInterface {
    name = 'Initial1779845425309'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "compiler_implementancion" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "compiler_id" integer NOT NULL, "implementancion_id" integer NOT NULL, CONSTRAINT "PK_b020ad33d0df373e5c9f1505e72" PRIMARY KEY ("compiler_id", "implementancion_id"))`);
        await queryRunner.query(`CREATE TABLE "compiler" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" character varying NOT NULL, "version" character varying NOT NULL, CONSTRAINT "UQ_36a09424ef7484b434bafca5827" UNIQUE ("name", "version"), CONSTRAINT "PK_db2bd64ab4e0d8cfe70fc5d6de0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "compiler_function" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "compiler_id" integer NOT NULL, "function_id" integer NOT NULL, CONSTRAINT "PK_8989d90b15852f0412973138f54" PRIMARY KEY ("compiler_id", "function_id"))`);
        await queryRunner.query(`CREATE TABLE "function" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" character varying NOT NULL, "implementicion_id" integer NOT NULL, CONSTRAINT "UQ_54c908b8bc8dbc4c3db3a80dc79" UNIQUE ("name", "implementicion_id"), CONSTRAINT "PK_6e085d059b4227aab09e8a5b05e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "implementancion" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" character varying NOT NULL, "version" character varying NOT NULL, CONSTRAINT "UQ_d34271806dfc031ab9d0116bbcf" UNIQUE ("name", "version"), CONSTRAINT "PK_455ad17167e5c565085ee95e316" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "directive_implementancion" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "directive_id" integer NOT NULL, "implementancion_id" integer NOT NULL, CONSTRAINT "PK_c8f13015dc284344e80454469d4" PRIMARY KEY ("directive_id", "implementancion_id"))`);
        await queryRunner.query(`CREATE TABLE "directive" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" character varying NOT NULL, "description" character varying NOT NULL, "sintax" text NOT NULL, "regex" character varying NOT NULL, "open_mp_id" integer NOT NULL, CONSTRAINT "UQ_6215925b8bd11df672babb14894" UNIQUE ("name", "open_mp_id"), CONSTRAINT "PK_399676ede08f26af35a9c460a09" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "open_mp" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "version" character varying NOT NULL, CONSTRAINT "UQ_1f40a3d47919666969d84b3f76f" UNIQUE ("version"), CONSTRAINT "PK_b5d7deb3bc49de0b9f123b2fe81" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "compiler_implementancion" ADD CONSTRAINT "FK_bfe8cbe412d62724f7b47db276a" FOREIGN KEY ("compiler_id") REFERENCES "compiler"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "compiler_implementancion" ADD CONSTRAINT "FK_12b6b3fec8fbb2d5c1bda097b31" FOREIGN KEY ("implementancion_id") REFERENCES "implementancion"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "compiler_function" ADD CONSTRAINT "FK_9df2f98ce4e4a4a818881e80ae9" FOREIGN KEY ("compiler_id") REFERENCES "compiler"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "compiler_function" ADD CONSTRAINT "FK_36db445028bc467507a3ccb565e" FOREIGN KEY ("function_id") REFERENCES "function"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "function" ADD CONSTRAINT "FK_424ad69abc0d91229d9199dd1ac" FOREIGN KEY ("implementicion_id") REFERENCES "implementancion"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "directive_implementancion" ADD CONSTRAINT "FK_0f4aece9c904cf8ca74f5269b0f" FOREIGN KEY ("directive_id") REFERENCES "directive"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "directive_implementancion" ADD CONSTRAINT "FK_2010c211911437f839cf1ff702b" FOREIGN KEY ("implementancion_id") REFERENCES "implementancion"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "directive" ADD CONSTRAINT "FK_07f483c5bbe1322eaa55733ce2c" FOREIGN KEY ("open_mp_id") REFERENCES "open_mp"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "directive" DROP CONSTRAINT "FK_07f483c5bbe1322eaa55733ce2c"`);
        await queryRunner.query(`ALTER TABLE "directive_implementancion" DROP CONSTRAINT "FK_2010c211911437f839cf1ff702b"`);
        await queryRunner.query(`ALTER TABLE "directive_implementancion" DROP CONSTRAINT "FK_0f4aece9c904cf8ca74f5269b0f"`);
        await queryRunner.query(`ALTER TABLE "function" DROP CONSTRAINT "FK_424ad69abc0d91229d9199dd1ac"`);
        await queryRunner.query(`ALTER TABLE "compiler_function" DROP CONSTRAINT "FK_36db445028bc467507a3ccb565e"`);
        await queryRunner.query(`ALTER TABLE "compiler_function" DROP CONSTRAINT "FK_9df2f98ce4e4a4a818881e80ae9"`);
        await queryRunner.query(`ALTER TABLE "compiler_implementancion" DROP CONSTRAINT "FK_12b6b3fec8fbb2d5c1bda097b31"`);
        await queryRunner.query(`ALTER TABLE "compiler_implementancion" DROP CONSTRAINT "FK_bfe8cbe412d62724f7b47db276a"`);
        await queryRunner.query(`DROP TABLE "open_mp"`);
        await queryRunner.query(`DROP TABLE "directive"`);
        await queryRunner.query(`DROP TABLE "directive_implementancion"`);
        await queryRunner.query(`DROP TABLE "implementancion"`);
        await queryRunner.query(`DROP TABLE "function"`);
        await queryRunner.query(`DROP TABLE "compiler_function"`);
        await queryRunner.query(`DROP TABLE "compiler"`);
        await queryRunner.query(`DROP TABLE "compiler_implementancion"`);
    }

}
